### PR TITLE
Replace light-mode screenshot with dark-mode

### LINKED ISSUE #3: mdoc-quickstart: Request: add dark-mode screenshot for dark-mode users
I tend to use dark mode on all my computers when the sun goes down. While this makes GitHub more pleasant to read after dark, bright-white images can be blinding. Would you consider replacing `mdoc-examples.png` with a dark version, or having the browser choose with something like the following?

```markdown
<picture>
 <source srcset='mdoc-examples-dark.png' media='(prefers-color-scheme: dark)' type='image/png'>
 <img src='mdoc-examples-light.png' alt='Image of the mdoc-examples.7 man page'>
</picture>
```

I'd happily supply a pair of my own, but macOS' own manual page displayer is in monochrome, which is surprisingly less interesting than what Gentoo generates.

### PR DESCRIPTION
**Pull request by adiabatic**
Closes #3.

I tried making the screenshot pair responsive with `picture`/`source`. Unfortunately, GitHub rewrites image URLs for standard Markdown links (``) but not URLs in HTML.

### CODE REVIEW

**Comment by flexibeast** [comment]
Thanks for doing this! However, with regards to the PR's title, i'm not willing to simply replace a 'light'-mode screencap with a 'dark' one, given that i'm one of a number of people who find 'dark' themes difficult to read. My preference is to find some way of including both regardless of GitHub's limitations. So to that end, i've changed the guide to now read:

> The resulting formatted output is visible in the following screencaps:
>
> [for dark-themed environments](https://github.com/flexibeast/guides/blob/master/mdoc-examples-dark.png)
> [for light-themed environments](https://github.com/flexibeast/guides/blob/master/mdoc-examples-light.png)

using the screencap you provided. Does that work for you?

**Comment by adiabatic** [comment]
Works for me. If you'd like my version in light mode, here's the file:

mdoc-examples-7-light

**Comment by adiabatic** [comment]
Sounds good to me. Here are a pair of light and dark screenshots if you're into matching pairs:

mdoc-examples-7-light

mdoc-examples-7-dark

**Comment by flexibeast** [comment]
> Sounds good to me.

Great, i'll close this PR then.

> Here are a pair of light and dark screenshots if you're into matching pairs:

At this stage i won't use the screencap pair you provided, but might end up doing so at some point in the future. :-)

**Pull request closed without merging**
